export const products = [
    { id: 1, name: "Wireless Earbuds", price: "$29.99", image: "https://via.placeholder.com/150", description: "High-quality sound with noise cancellation.", category: "Electronics" },
    { id: 2, name: "Smartphone Stand", price: "$15.99", image: "https://via.placeholder.com/150", description: "Adjustable stand for smartphones and tablets.", category: "Accessories" },
    { id: 3, name: "Bluetooth Speaker", price: "$49.99", image: "https://via.placeholder.com/150", description: "Portable speaker with deep bass and long battery life.", category: "Electronics" },
    { id: 4, name: "Fitness Tracker", price: "$39.99", image: "https://via.placeholder.com/150", description: "Track your steps, heart rate, and more.", category: "Fitness" },
    { id: 5, name: "Laptop Sleeve", price: "$19.99", image: "https://via.placeholder.com/150", description: "Protective sleeve for laptops up to 15 inches.", category: "Accessories" },
    { id: 6, name: "Portable Charger", price: "$24.99", image: "https://via.placeholder.com/150", description: "Compact power bank with fast charging.", category: "Electronics" },
    { id: 7, name: "USB-C Hub", price: "$34.99", image: "https://via.placeholder.com/150", description: "Multi-port adapter with HDMI, USB, and SD card slots.", category: "Accessories" },
    { id: 8, name: "Wireless Mouse", price: "$19.99", image: "https://via.placeholder.com/150", description: "Ergonomic mouse with customizable buttons.", category: "Accessories" },
    { id: 9, name: "Mechanical Keyboard", price: "$69.99", image: "https://via.placeholder.com/150", description: "Tactile switches for a satisfying typing experience.", category: "Electronics" },
    { id: 10, name: "Noise-Cancelling Headphones", price: "$99.99", image: "https://via.placeholder.com/150", description: "Over-ear headphones with active noise cancellation.", category: "Electronics" },
    { id: 11, name: "Smart Home Hub", price: "$79.99", image: "https://via.placeholder.com/150", description: "Control your smart home devices from one place.", category: "Smart Home" },
    { id: 12, name: "4K Monitor", price: "$299.99", image: "https://via.placeholder.com/150", description: "Ultra HD monitor with stunning color accuracy.", category: "Electronics" },
    { id: 13, name: "Gaming Chair", price: "$199.99", image: "https://via.placeholder.com/150", description: "Comfortable chair designed for long gaming sessions.", category: "Furniture" },
    { id: 14, name: "Action Camera", price: "$149.99", image: "https://via.placeholder.com/150", description: "Capture your adventures in high definition.", category: "Electronics" },
    { id: 15, name: "Smart Light Bulbs", price: "$49.99", image: "https://via.placeholder.com/150", description: "LED bulbs that you can control with your smartphone.", category: "Smart Home" },
    { id: 16, name: "Electric Toothbrush", price: "$59.99", image: "https://via.placeholder.com/150", description: "Ensure optimal dental hygiene with this smart toothbrush.", category: "Personal Care" },
    { id: 17, name: "Robot Vacuum", price: "$229.99", image: "https://via.placeholder.com/150", description: "Automatic vacuum that keeps your floors clean.", category: "Smart Home" },
    { id: 18, name: "Instant Pot", price: "$89.99", image: "https://via.placeholder.com/150", description: "Multi-functional cooker for quick and easy meals.", category: "Kitchen" },
    { id: 19, name: "Air Purifier", price: "$129.99", image: "https://via.placeholder.com/150", description: "Keep your home air clean and allergen-free.", category: "Home Appliances" },
    { id: 20, name: "Smart Thermostat", price: "$149.99", image: "https://via.placeholder.com/150", description: "Control your home's temperature with your voice or phone.", category: "Smart Home" },
    { id: 21, name: "Electric Kettle", price: "$29.99", image: "https://via.placeholder.com/150", description: "Boil water quickly and efficiently.", category: "Kitchen" },
    { id: 22, name: "Smart Doorbell", price: "$99.99", image: "https://via.placeholder.com/150", description: "See who is at your door from your smartphone.", category: "Smart Home" },
    { id: 23, name: "Outdoor Security Camera", price: "$129.99", image: "https://via.placeholder.com/150", description: "Monitor your home's exterior with high-definition video.", category: "Smart Home" },
    { id: 24, name: "Air Fryer", price: "$69.99", image: "https://via.placeholder.com/150", description: "Cook healthier meals with little to no oil.", category: "Kitchen" },
    { id: 25, name: "Electric Shaver", price: "$49.99", image: "https://via.placeholder.com/150", description: "Smooth and comfortable shave every time.", category: "Personal Care" },
    { id: 26, name: "Cordless Drill", price: "$79.99", image: "https://via.placeholder.com/150", description: "Powerful drill for all your DIY projects.", category: "Tools" },
    { id: 27, name: "Smart Plug", price: "$19.99", image: "https://via.placeholder.com/150", description: "Control your devices remotely with this smart plug.", category: "Smart Home" },
    { id: 28, name: "Pressure Washer", price: "$149.99", image: "https://via.placeholder.com/150", description: "High-pressure cleaning for your home and garden.", category: "Tools" },
    { id: 29, name: "Standing Desk", price: "$299.99", image: "https://via.placeholder.com/150", description: "Adjustable desk for a healthier work environment.", category: "Furniture" },
    { id: 30, name: "3D Printer", price: "$399.99", image: "https://via.placeholder.com/150", description: "Print your own 3D models at home.", category: "Electronics" },
    { id: 31, name: "Video Doorbell", price: "$149.99", image: "https://via.placeholder.com/150", description: "Keep an eye on your doorstep with live video.", category: "Smart Home" },
    { id: 32, name: "Smart Scale", price: "$49.99", image: "https://via.placeholder.com/150", description: "Track your weight and body composition.", category: "Fitness" },
    { id: 33, name: "Home Security System", price: "$249.99", image: "https://via.placeholder.com/150", description: "Protect your home with this comprehensive security system.", category: "Smart Home" },
    { id: 34, name: "Portable Projector", price: "$199.99", image: "https://via.placeholder.com/150", description: "Take your movies and presentations anywhere.", category: "Electronics" },
    { id: 35, name: "Smartwatch", price: "$199.99", image: "https://via.placeholder.com/150", description: "Stay connected and track your fitness on the go.", category: "Fitness" },
    { id: 36, name: "LED Strip Lights", price: "$29.99", image: "https://via.placeholder.com/150", description: "Decorate your space with these colorful LED lights.", category: "Home Decor" },
    { id: 37, name: "Wireless Charger", price: "$39.99", image: "https://via.placeholder.com/150", description: "Charge your devices without any cables.", category: "Electronics" },
    { id: 38, name: "Digital Picture Frame", price: "$89.99", image: "https://via.placeholder.com/150", description: "Display your favorite photos in high definition.", category: "Home Decor" },
    { id: 39, name: "Electric Scooter", price: "$499.99", image: "https://via.placeholder.com/150", description: "Eco-friendly transportation for your daily commute.", category: "Transport" },
    { id: 40, name: "Gaming Headset", price: "$79.99", image: "https://via.placeholder.com/150", description: "Immersive sound for your gaming sessions.", category: "Electronics" },
    { id: 41, name: "Smart Coffee Maker", price: "$99.99", image: "https://via.placeholder.com/150", description: "Brew your coffee with a touch of a button.", category: "Kitchen" },
    { id: 42, name: "Smart Mirror", price: "$299.99", image: "https://via.placeholder.com/150", description: "Interactive mirror with built-in display.", category: "Home Decor" },
    { id: 43, name: "Electric Bike", price: "$999.99", image: "https://via.placeholder.com/150", description: "Ride effortlessly with this electric bike.", category: "Transport" },
    { id: 44, name: "Robot Mop", price: "$249.99", image: "https://via.placeholder.com/150", description: "Automated mopping for spotless floors.", category: "Smart Home" },
    { id: 45, name: "Smart Lock", price: "$199.99", image: "https://via.placeholder.com/150", description: "Secure your home with this smart lock.", category: "Smart Home" },
    { id: 46, name: "Noise Machine", price: "$49.99", image: "https://via.placeholder.com/150", description: "Create a peaceful environment with soothing sounds.", category: "Home Decor" },
    { id: 47, name: "Electric Blanket", price: "$79.99", image: "https://via.placeholder.com/150", description: "Stay warm and cozy with this electric blanket.", category: "Home Decor" },
    { id: 48, name: "Home Theater System", price: "$399.99", image: "https://via.placeholder.com/150", description: "Experience cinema-quality sound at home.", category: "Electronics" },
    { id: 49, name: "Water Filter", price: "$29.99", image: "https://via.placeholder.com/150", description: "Ensure clean and safe drinking water.", category: "Kitchen" },
    { id: 50, name: "Electric Grill", price: "$99.99", image: "https://via.placeholder.com/150", description: "Grill your favorite foods indoors.", category: "Kitchen" },
    { id: 51, name: "Smart Door Lock", price: "$179.99", image: "https://via.placeholder.com/150", description: "Lock and unlock your door with your smartphone.", category: "Smart Home" },
    { id: 52, name: "Video Baby Monitor", price: "$149.99", image: "https://via.placeholder.com/150", description: "Keep an eye on your baby with live video.", category: "Smart Home" },
    { id: 53, name: "Wine Cooler", price: "$249.99", image: "https://via.placeholder.com/150", description: "Keep your wine at the perfect temperature.", category: "Kitchen" },
    { id: 54, name: "Digital Assistant", price: "$49.99", image: "https://via.placeholder.com/150", description: "Voice-activated assistant for your smart home.", category: "Smart Home" },
    { id: 55, name: "Electric Toothbrush", price: "$59.99", image: "https://via.placeholder.com/150", description: "Ensure optimal dental hygiene with this smart toothbrush.", category: "Personal Care" },
    { id: 56, name: "Pet Feeder", price: "$99.99", image: "https://via.placeholder.com/150", description: "Automate your pet's feeding schedule.", category: "Pet Supplies" },
    { id: 57, name: "Smart Scale", price: "$49.99", image: "https://via.placeholder.com/150", description: "Track your weight and body composition.", category: "Fitness" },
    { id: 58, name: "Smart Home Hub", price: "$79.99", image: "https://via.placeholder.com/150", description: "Control your smart home devices from one place.", category: "Smart Home" },
    { id: 59, name: "Cordless Vacuum", price: "$199.99", image: "https://via.placeholder.com/150", description: "Lightweight and powerful vacuum cleaner.", category: "Home Appliances" },
    { id: 60, name: "Smart Oven", price: "$299.99", image: "https://via.placeholder.com/150", description: "Cook your meals perfectly with this smart oven.", category: "Kitchen" },
    { id: 61, name: "Smart Light Switch", price: "$29.99", image: "https://via.placeholder.com/150", description: "Control your lights with your voice or phone.", category: "Smart Home" },
    { id: 62, name: "Sous Vide Cooker", price: "$129.99", image: "https://via.placeholder.com/150", description: "Cook your food to perfection with sous vide.", category: "Kitchen" },
    { id: 63, name: "Digital Meat Thermometer", price: "$29.99", image: "https://via.placeholder.com/150", description: "Ensure your meat is cooked to the perfect temperature.", category: "Kitchen" },
    { id: 64, name: "Smart Garage Door Opener", price: "$99.99", image: "https://via.placeholder.com/150", description: "Open and close your garage door with your smartphone.", category: "Smart Home" },
    { id: 65, name: "Indoor Garden", price: "$199.99", image: "https://via.placeholder.com/150", description: "Grow fresh herbs and vegetables indoors.", category: "Home Decor" },
    { id: 66, name: "Electric Scooter", price: "$499.99", image: "https://via.placeholder.com/150", description: "Eco-friendly transportation for your daily commute.", category: "Transport" },
    { id: 67, name: "Wireless Security Camera", price: "$149.99", image: "https://via.placeholder.com/150", description: "Monitor your home with this wireless camera.", category: "Smart Home" },
    { id: 68, name: "Smart Thermostat", price: "$149.99", image: "https://via.placeholder.com/150", description: "Control your home's temperature with your voice or phone.", category: "Smart Home" },
    { id: 69, name: "Portable Air Conditioner", price: "$299.99", image: "https://via.placeholder.com/150", description: "Cool your room quickly with this portable AC.", category: "Home Appliances" },
    { id: 70, name: "Smart Pet Camera", price: "$149.99", image: "https://via.placeholder.com/150", description: "Keep an eye on your pet with live video.", category: "Pet Supplies" },
    { id: 71, name: "Electric Standing Desk", price: "$399.99", image: "https://via.placeholder.com/150", description: "Adjustable desk for a healthier work environment.", category: "Furniture" },
    { id: 72, name: "Smart Bed", price: "$999.99", image: "https://via.placeholder.com/150", description: "Adjustable bed with smart features.", category: "Furniture" },
    { id: 73, name: "Digital Whiteboard", price: "$299.99", image: "https://via.placeholder.com/150", description: "Interactive whiteboard for your office or home.", category: "Office Supplies" },
    { id: 74, name: "Smart Refrigerator", price: "$999.99", image: "https://via.placeholder.com/150", description: "Keep your food fresh with this smart fridge.", category: "Home Appliances" },
    { id: 75, name: "Wireless Charging Pad", price: "$49.99", image: "https://via.placeholder.com/150", description: "Charge your devices without any cables.", category: "Electronics" },
    { id: 76, name: "Smart Light Bulbs", price: "$49.99", image: "https://via.placeholder.com/150", description: "LED bulbs that you can control with your smartphone.", category: "Smart Home" },
    { id: 77, name: "Electric Pressure Cooker", price: "$89.99", image: "https://via.placeholder.com/150", description: "Cook your meals quickly and easily.", category: "Kitchen" },
    { id: 78, name: "Robot Lawn Mower", price: "$999.99", image: "https://via.placeholder.com/150", description: "Automated lawn mowing for a perfect yard.", category: "Garden" },
    { id: 79, name: "Smart Water Bottle", price: "$39.99", image: "https://via.placeholder.com/150", description: "Track your hydration with this smart bottle.", category: "Fitness" }
];