export const products = [
    { name: "Wireless Earbuds", price: "$29.99", image: "https://via.placeholder.com/150", description: "High-quality sound with noise cancellation." },
    { name: "Smartphone Stand", price: "$15.99", image: "https://via.placeholder.com/150", description: "Adjustable stand for smartphones and tablets." },
    { name: "Bluetooth Speaker", price: "$49.99", image: "https://via.placeholder.com/150", description: "Portable speaker with deep bass and long battery life." },
    { name: "Fitness Tracker", price: "$39.99", image: "https://via.placeholder.com/150", description: "Track your steps, heart rate, and more." },
    { name: "Laptop Sleeve", price: "$19.99", image: "https://via.placeholder.com/150", description: "Protective sleeve for laptops up to 15 inches." },
    { name: "Portable Charger", price: "$24.99", image: "https://via.placeholder.com/150", description: "Compact power bank with fast charging." },
    { name: "USB-C Hub", price: "$34.99", image: "https://via.placeholder.com/150", description: "Multi-port adapter with HDMI, USB, and SD card slots." },
    { name: "Wireless Mouse", price: "$19.99", image: "https://via.placeholder.com/150", description: "Ergonomic mouse with customizable buttons." },
    { name: "Mechanical Keyboard", price: "$69.99", image: "https://via.placeholder.com/150", description: "Tactile switches for a satisfying typing experience." },
    { name: "Noise-Cancelling Headphones", price: "$99.99", image: "https://via.placeholder.com/150", description: "Over-ear headphones with active noise cancellation." },
    { name: "Smart Home Hub", price: "$79.99", image: "https://via.placeholder.com/150", description: "Control your smart home devices from one place." },
    { name: "4K Monitor", price: "$299.99", image: "https://via.placeholder.com/150", description: "Ultra HD monitor with stunning color accuracy." },
    { name: "Gaming Chair", price: "$199.99", image: "https://via.placeholder.com/150", description: "Comfortable chair designed for long gaming sessions." },
    { name: "Action Camera", price: "$149.99", image: "https://via.placeholder.com/150", description: "Capture your adventures in high definition." },
    { name: "Smart Light Bulbs", price: "$49.99", image: "https://via.placeholder.com/150", description: "LED bulbs that you can control with your smartphone." },
    { name: "Electric Toothbrush", price: "$59.99", image: "https://via.placeholder.com/150", description: "Ensure optimal dental hygiene with this smart toothbrush." },
    { name: "Robot Vacuum", price: "$229.99", image: "https://via.placeholder.com/150", description: "Automatic vacuum that keeps your floors clean." },
    { name: "Instant Pot", price: "$89.99", image: "https://via.placeholder.com/150", description: "Multi-functional cooker for quick and easy meals." },
    { name: "Air Purifier", price: "$129.99", image: "https://via.placeholder.com/150", description: "Keep your home air clean and allergen-free." },
    { name: "Smart Thermostat", price: "$149.99", image: "https://via.placeholder.com/150", description: "Control your home's temperature with your voice or phone." },
    { name: "Electric Kettle", price: "$29.99", image: "https://via.placeholder.com/150", description: "Boil water quickly and efficiently." },
    { name: "Smart Doorbell", price: "$99.99", image: "https://via.placeholder.com/150", description: "See who is at your door from your smartphone." },
    { name: "Outdoor Security Camera", price: "$129.99", image: "https://via.placeholder.com/150", description: "Monitor your home's exterior with high-definition video." },
    { name: "Air Fryer", price: "$69.99", image: "https://via.placeholder.com/150", description: "Cook healthier meals with little to no oil." },
    { name: "Electric Shaver", price: "$49.99", image: "https://via.placeholder.com/150", description: "Smooth and comfortable shave every time." },
    { name: "Cordless Drill", price: "$79.99", image: "https://via.placeholder.com/150", description: "Powerful drill for all your DIY projects." },
    { name: "Smart Plug", price: "$19.99", image: "https://via.placeholder.com/150", description: "Control your devices remotely with this smart plug." },
    { name: "Pressure Washer", price: "$149.99", image: "https://via.placeholder.com/150", description: "High-pressure cleaning for your home and garden." },
    { name: "Standing Desk", price: "$299.99", image: "https://via.placeholder.com/150", description: "Adjustable desk for a healthier work environment." },
    { name: "3D Printer", price: "$399.99", image: "https://via.placeholder.com/150", description: "Print your own 3D models at home." },
    { name: "Video Doorbell", price: "$149.99", image: "https://via.placeholder.com/150", description: "Keep an eye on your doorstep with live video." },
    { name: "Smart Scale", price: "$49.99", image: "https://via.placeholder.com/150", description: "Track your weight and body composition." },
    { name: "Home Security System", price: "$249.99", image: "https://via.placeholder.com/150", description: "Protect your home with this comprehensive security system." },
    { name: "Portable Projector", price: "$199.99", image: "https://via.placeholder.com/150", description: "Take your movies and presentations anywhere." },
    { name: "Smartwatch", price: "$199.99", image: "https://via.placeholder.com/150", description: "Stay connected and track your fitness on the go." },
    { name: "LED Strip Lights", price: "$29.99", image: "https://via.placeholder.com/150", description: "Decorate your space with these colorful LED lights." },
    { name: "Wireless Charger", price: "$39.99", image: "https://via.placeholder.com/150", description: "Charge your devices without any cables." },
    { name: "Digital Picture Frame", price: "$89.99", image: "https://via.placeholder.com/150", description: "Display your favorite photos in high definition." },
    { name: "Electric Scooter", price: "$499.99", image: "https://via.placeholder.com/150", description: "Eco-friendly transportation for your daily commute." },
    { name: "Gaming Headset", price: "$79.99", image: "https://via.placeholder.com/150", description: "Immersive sound for your gaming sessions." },
    { name: "Smart Coffee Maker", price: "$99.99", image: "https://via.placeholder.com/150", description: "Brew your coffee with a touch of a button." },
    { name: "Smart Mirror", price: "$299.99", image: "https://via.placeholder.com/150", description: "Interactive mirror with built-in display." },
    { name: "Electric Bike", price: "$999.99", image: "https://via.placeholder.com/150", description: "Ride effortlessly with this electric bike." },
    { name: "Robot Mop", price: "$249.99", image: "https://via.placeholder.com/150", description: "Automated mopping for spotless floors." },
    { name: "Smart Lock", price: "$199.99", image: "https://via.placeholder.com/150", description: "Secure your home with this smart lock." },
    { name: "Noise Machine", price: "$49.99", image: "https://via.placeholder.com/150", description: "Create a peaceful environment with soothing sounds." },
    { name: "Electric Blanket", price: "$79.99", image: "https://via.placeholder.com/150", description: "Stay warm and cozy with this electric blanket." },
    { name: "Home Theater System", price: "$399.99", image: "https://via.placeholder.com/150", description: "Experience cinema-quality sound at home." },
    { name: "Water Filter", price: "$29.99", image: "https://via.placeholder.com/150", description: "Ensure clean and safe drinking water." },
    { name: "Electric Grill", price: "$99.99", image: "https://via.placeholder.com/150", description: "Grill your favorite foods indoors." },
    { name: "Smart Door Lock", price: "$179.99", image: "https://via.placeholder.com/150", description: "Lock and unlock your door with your smartphone." },
    { name: "Video Baby Monitor", price: "$149.99", image: "https://via.placeholder.com/150", description: "Keep an eye on your baby with live video." },
    { name: "Wine Cooler", price: "$249.99", image: "https://via.placeholder.com/150", description: "Keep your wine at the perfect temperature." },
    { name: "Digital Assistant", price: "$49.99", image: "https://via.placeholder.com/150", description: "Voice-activated assistant for your smart home." },
    { name: "Electric Toothbrush", price: "$59.99", image: "https://via.placeholder.com/150", description: "Ensure optimal dental hygiene with this smart toothbrush." },
    { name: "Pet Feeder", price: "$99.99", image: "https://via.placeholder.com/150", description: "Automate your pet's feeding schedule." },
    { name: "Smart Scale", price: "$49.99", image: "https://via.placeholder.com/150", description: "Track your weight and body composition." },
    { name: "Smart Home Hub", price: "$79.99", image: "https://via.placeholder.com/150", description: "Control your smart home devices from one place." },
    { name: "Cordless Vacuum", price: "$199.99", image: "https://via.placeholder.com/150", description: "Lightweight and powerful vacuum cleaner." },
    { name: "Smart Oven", price: "$299.99", image: "https://via.placeholder.com/150", description: "Cook your meals perfectly with this smart oven." },
    { name: "Smart Light Switch", price: "$29.99", image: "https://via.placeholder.com/150", description: "Control your lights with your voice or phone." },
    { name: "Sous Vide Cooker", price: "$129.99", image: "https://via.placeholder.com/150", description: "Cook your food to perfection with sous vide." },
    { name: "Digital Meat Thermometer", price: "$29.99", image: "https://via.placeholder.com/150", description: "Ensure your meat is cooked to the perfect temperature." },
    { name: "Smart Garage Door Opener", price: "$99.99", image: "https://via.placeholder.com/150", description: "Open and close your garage door with your smartphone." },
    { name: "Indoor Garden", price: "$199.99", image: "https://via.placeholder.com/150", description: "Grow fresh herbs and vegetables indoors." },
    { name: "Electric Scooter", price: "$499.99", image: "https://via.placeholder.com/150", description: "Eco-friendly transportation for your daily commute." },
    { name: "Wireless Security Camera", price: "$149.99", image: "https://via.placeholder.com/150", description: "Monitor your home with this wireless camera." },
    { name: "Smart Thermostat", price: "$149.99", image: "https://via.placeholder.com/150", description: "Control your home's temperature with your voice or phone." },
    { name: "Portable Air Conditioner", price: "$299.99", image: "https://via.placeholder.com/150", description: "Cool your room quickly with this portable AC." },
    { name: "Smart Pet Camera", price: "$149.99", image: "https://via.placeholder.com/150", description: "Keep an eye on your pet with live video." },
    { name: "Electric Standing Desk", price: "$399.99", image: "https://via.placeholder.com/150", description: "Adjustable desk for a healthier work environment." },
    { name: "Smart Bed", price: "$999.99", image: "https://via.placeholder.com/150", description: "Adjustable bed with smart features." },
    { name: "Digital Whiteboard", price: "$299.99", image: "https://via.placeholder.com/150", description: "Interactive whiteboard for your office or home." },
    { name: "Smart Refrigerator", price: "$999.99", image: "https://via.placeholder.com/150", description: "Keep your food fresh with this smart fridge." },
    { name: "Wireless Charging Pad", price: "$49.99", image: "https://via.placeholder.com/150", description: "Charge your devices without any cables." },
    { name: "Smart Light Bulbs", price: "$49.99", image: "https://via.placeholder.com/150", description: "LED bulbs that you can control with your smartphone." },
    { name: "Electric Pressure Cooker", price: "$89.99", image: "https://via.placeholder.com/150", description: "Cook your meals quickly and easily." },
    { name: "Robot Lawn Mower", price: "$999.99", image: "https://via.placeholder.com/150", description: "Automated lawn mowing for a perfect yard." },
    { name: "Smart Water Bottle", price: "$39.99", image: "https://via.placeholder.com/150", description: "Track your hydration with this smart bottle." }
];